[IMP] apps-store
OCA/apps-store pull request #15
Opened 2018-10-01 14:50 UTC by oscarolar

- Shop:
  * Removed filter by author.
  * Added a more informative placeholder to the searchbox
  * Added categories of apps to public categories.
  * Added a filter `All` option for categories dropdown.
  * Removed sort by price.

- Changed the way products are created, now products are related
to their correspondant category. (used the ones from Odoo.com/apps)

- On PDP added the version of the app if it has no variants.

2018-10-01 14:50 UTC, oscarolar commented
cc @bizzappdev @elicoidal

2018-10-01 15:33 UTC, elicoidal approved these changes
LGTM.
Might bump the version number

2018-10-01 16:32 UTC, StephanRozendaal approved these changes

2018-10-02 07:13 UTC, elicoidal commented
Please check Travis.

2018-10-02 08:02 UTC, oscarolar commented
To make the test pass
depends: https://github.com/OCA/interface-github/pull/22

2018-10-02 09:04 UTC, bizzappdev requested changes
only last thing for supporting "Other" category if it is not able to find the category based on module version category.

2018-10-02 09:04 UTC, bizzappdev commented on apps_product_creator/models/odoo_module.py
> +            [('name','=',version_categ.name)], limit=1)
@oscarolar  don't your thing that we need to add Other as a category in case we are not able to find a website category based on version category.

2018-10-02 09:15 UTC, bizzappdev approved these changes
LGTM

2018-10-02 11:26 UTC, elicoidal commented
Please fix conflicts

2018-10-02 11:33 UTC, merged