[11.0][MIG] apps_product_creator: Migration to 11.0
OCA/apps-store pull request #9
Opened 2018-04-12 10:39 UTC by tarteo

2018-04-28 09:45 UTC, elicoidal requested changes
Thanks!
small details
IMO quite straightforward but no test.

2018-04-28 09:45 UTC, elicoidal commented on .idea/apps-store.iml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove this file or edit gitignore

2018-04-28 09:45 UTC, elicoidal commented on apps_product_creator/demo/product_attribute.xml
> +    <record id="attribute_odoo_version" model="product.attribute">
Following https://github.com/OCA/apps-store/issues/8#issuecomment-377769239 should be data not demo

2018-04-28 09:45 UTC, elicoidal commented on apps_product_creator/views/view_odoo_module.xml
> +                <button type="object" class="oe_stat_button" icon="fa-arrows-v" name="action_view_products" attrs="{'invisible': [('product_qty', '=', 0)]}">
can you improve the format for readability?

2018-04-28 09:45 UTC, elicoidal commented on apps_product_creator/views/view_product_product.xml
> +                <page string="Module Informations" id="module_informations" attrs="{'invisible':[('odoo_module_version_id','=',False)]}">
and here?

2018-05-03 09:58 UTC, tarteo commented
@elicoidal Thanks for your review! I applied the improvements.

2018-05-23 10:40 UTC, elicoidal approved these changes
LGTM. needs test

2018-05-23 10:40 UTC, elicoidal commented
Please take care of travis too

2018-05-23 10:45 UTC, elicoidal commented
@tafaRU @espo-tony @hurrinico @acsonefho can you help review here?

2018-05-23 11:09 UTC, acsonefho commented
Code LGTM (not tested)

2018-05-23 11:49 UTC, acsonefho approved these changes

2018-05-24 00:38 UTC, elicoidal commented
thanks for the review @acsonefho !

2018-05-24 06:30 UTC, espo-tony commented
Code LGTM too.

2018-05-24 06:31 UTC, espo-tony approved these changes

2018-05-24 07:59 UTC, elicoidal commented
Not sure who could help in the testing, any idea?

2018-06-12 10:07 UTC, astirpe commented
Add file `oca_dependencies.txt` (like in V10).  Let's see if it turns green ...

2018-06-12 17:02 UTC, tarteo commented
@astirpe It turned green, thanks!!

2018-06-13 09:54 UTC, bizzappdev commented
@tarteo just a note we have changed few things in V10 in https://github.com/OCA/apps-store/pull/10/files which might later have to be migrated also.

2018-06-26 08:47 UTC, gdgellatly commented
@elicoidal is this ready for merge?

\cc @jgrandguillaume

2018-06-26 08:56 UTC, elicoidal commented
Yep

2018-06-26 08:56 UTC, merged